/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChipsDialog: typeof import('./src/components/chips-dialog.vue')['default']
    ChipsPixelswitch: typeof import('./src/components/chips-pixelswitch.vue')['default']
    ChipsPixelSwitch: typeof import('./src/components/Chips-PixelSwitch.vue')['default']
    ChipsStatusbar: typeof import('./src/components/chips-statusbar.vue')['default']
    ChipsToast: typeof import('./src/components/chips-toast.vue')['default']
    PixelClock: typeof import('./src/components/widgets/PixelClock.vue')['default']
    PixelSwitch: typeof import('./src/components/PixelSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarButtonround: typeof import('@varlet/ui')['_ButtonroundComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarSnackbar: typeof import('@varlet/ui')['_SnackbarComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
  }
}
